---
- name: Import Python script
  ansible.builtin.script: files/parse_store_list.py {{ store_list }}
  args:
    executable: python3
  changed_when: false
  register: parsed_store_list

- name: Convert string to list
  ansible.builtin.set_fact:
    store_list_converted: "{{ parsed_store_list.stdout | from_json }}"

- name: Print converted list
  ansible.builtin.debug:
    var: store_list_converted

# needed to break the playbook so it prevents devices from still being pulled if the store_list_converted contains an item with empty strings
- name: Check if store_list_converted contains any empty strings
  ansible.builtin.fail:
    msg: "The store_list variable contains one or more empty strings."
  when: store_list_converted | select('match', '^$') | list | length > 0

- name: Send auth request to mdm and return token
  ansible.builtin.uri:
    url: "{{ mdm_auth_url }}"
    method: POST
    validate_certs: false
    return_content: true
    headers:
      Accept-Version: "1.0.0"
    body:
      clientSecret: "{{ mdm_clientSecret }}"
    body_format: json
  register: auth_response

- name: Auth token
  ansible.builtin.debug:
    var: auth_response.json

- name: Build kiosk URLs for each store in the list
  ansible.builtin.set_fact:
    kiosk_urls: "{{ kiosk_urls | default([]) + [mdm_kiosk_url + item] }}"
  loop: "{{ store_list_converted }}"

- name: Print kiosk URLs
  ansible.builtin.debug:
    var: kiosk_urls

- name: Send mdm request to get each site's kiosk info
  loop: "{{ kiosk_urls }}"
  ansible.builtin.uri:
    url: "{{ item }}"
    method: GET
    status_code:
      - 200
    validate_certs: false
    return_content: true
    headers:
      Accept: application/json
      Authorization: "{{ mdm_token }}"
  register: mdm_kiosk_response

- name: Print mdm_kiosk_response
  ansible.builtin.debug:
    var: mdm_kiosk_response

- name: Initialize list to hold all kiosk asset tags
  ansible.builtin.set_fact:
    kiosk_asset_tags: []

- name: Pull asset tags from all results
  ansible.builtin.set_fact:
    kiosk_asset_tags: "{{ kiosk_asset_tags + item.json.results | map(attribute='asset_tag') | list }}"
  loop: "{{ mdm_kiosk_response.results }}"
  when: item.json.results is defined

- name: Print all asset tags
  ansible.builtin.debug:
    var: kiosk_asset_tags

- name: Initialize list to hold store IDs
  ansible.builtin.set_fact:
    kiosk_stores: []

- name: Pull store ID from mdm_kiosk_response.results
  ansible.builtin.set_fact:
    kiosk_stores: "{{ kiosk_stores + item.json.results | map(attribute='name') | list }}"
  loop: "{{ mdm_kiosk_response.results }}"
  when: item.json.results is defined

- name: Print kiosk_stores list
  ansible.builtin.debug:
    var: kiosk_stores

- name: Initialize dictionary to hold kiosk mappings
  ansible.builtin.set_fact:
    kiosk_mapping: {}

- name: Create mapping of asset tags to store IDs
  ansible.builtin.set_fact:
    kiosk_mapping: "{{ kiosk_mapping | combine(
      dict(
        item.json.results
        | map(attribute='name')
        | zip(item.json.results | map(attribute='asset_tag'))
        | list
        )
      ) }}"
  loop: "{{ mdm_kiosk_response.results }}"
  when: item.json.results is defined

- name: Print kiosk_mapping
  ansible.builtin.debug:
    var: kiosk_mapping

- name: Reboot all kiosks
  loop: "{{ kiosk_mapping.values() | list }}"
  ansible.builtin.uri:
    url: "{{ mdm_reboot_url }}"
    method: POST
    validate_certs: false
    return_content: true
    headers:
      authPayload: "{{ auth_response.json.data.authPayload }}"
      Accept-Version: "1.0.0"
    body:
      deviceId: "{{ item }}"
    body_format: json
  register: reboot_response

- name: Print status code and response message for each item
  ansible.builtin.debug:
    msg: "Store: {{ kiosk_mapping | dict2items | selectattr('value', 'eq', item.item) | map(attribute='key') | first }} - Device ID: {{ item.item }} - Status Code: {{ item.status }} - Response Message: {{ item.json.message }}"
  loop: "{{ reboot_response.results }}"
